homeconnect:
  uri: "simulator.home-connect.com"
  homeappliancespath: "/api/homeappliances"
  tokenpath: "/security/oauth/token"
  programspath: "/api/homeappliances/<haid>/programs/available"
  clientsecret: "31DB0871FBA1A9ED1EE0B34108B55984FB4E04318C13C10FBA3B289D38747F3D"
  clientid: "22F5FAF6A84460284EA2304DD315B680E3AA0071B28F58CF12C8D499449CFD85"
  redirectUri: "http://localhost:8081/v1/authenticateHomeConnect"

flowxo:
  uri: "flowxo.com"
  webhookpath: "/hooks/a/735xrwpn"