#%RAML 1.0
title: gis-hc-integration-api
description : This API will be used on chatbot integration to integrate grunindex and Homeconnect account
baseUri: https://localhost:8081/gis-hc/v1
/findDishwasherPrograms:
  post:
    body:
      application/json:
        example:
          {
            "accessToken" : "refresh-token",
            "telegramUser" : "hayra"
          }
    responses:
      200:
        body:
          application/json:
            example:
              {
                "status": "200",
                "dishwasherInformation" : 
                {
                  "name": "Dishwasher Simulator",
                  "brand": "SIEMENS",
                  "vib": "HCS02DWH1",
                  "connected": true,
                  "type": "Dishwasher",
                  "enumber": "HCS02DWH1/03",
                  "haId": "SIEMENS-HCS02DWH1-DD5909DE1934",
                  "programs" : [
                    {
                      "key": "Dishcare.Dishwasher.Program.Eco50",
                      "constraints": {
                          "execution": "selectandstart"
                      }
                    },
                    {
                      "key": "Dishcare.Dishwasher.Program.Quick45",
                      "constraints": {
                        "execution": "selectandstart"
                      }
                    }
                  ]
                },
                "message" : "success"
              }
      500:
        body:
          application/json:
            example:
              {
                "status" : "500",
                "message" : "Internal server error"
              }
/setGrunStromEnergyForDevice:
  post:
    body:
      application/json:
        example:
          {
            "refresh-token" : "refresh-token",
            "telegram-user" : "hayra",
            "homeconnect-device-id": "homeconnect-device-id"
          }
    responses:
      200:
        body:
          application/json:
            example:
              {
                "status": "200",
                "message" : "success"
              }
      500:
        body:
          application/json:
            example:
              {
                "status" : "500",
                "message" : "Internal server error"
              }
/authenticateHomeConnect:
  get:
    queryParameters:
      code:
        type: string
      state:
        type: string
